language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
before_install:
  - gem update --system
  - gem --version # make sure rubygems actually were updated
  - mkdir /tmp/litmus
  - wget -O /tmp/litmus/litmus.tar.gz http://www.webdav.org/neon/litmus/litmus-0.13.tar.gz
  - tar -C /tmp/litmus -xvzf /tmp/litmus/litmus.tar.gz
  - cd /tmp/litmus/litmus-0.13
  - ./configure
before_script:
  - rm -rf /tmp/dav-file-store
  - mkdir /tmp/dav-file-store
script: test/script.sh
