language: ruby
rvm:
  - ree
before_install:
  - gem update --system
  - gem --version # make sure rubygems actually were updated
  - ./test/setup_script.sh
before_script:
  - rm -rf /tmp/dav-file-store
  - mkdir /tmp/dav-file-store
script: ./test/script.sh
